# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1udjn9sEicVQW7YDS53ZV7_gjgx0NIFeY
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
import tensorflow as tf

model = tf.keras.models.load_model("/F:/sos_tomato/vgg19_22_model.h5")

def chx(x1,x2,y1,y2,shx,shy):
    u=[x1,x2,y1,y2]
    for i in range(2):
        if(u[i]<0):
            u[i]=0
        if(u[i]>shx):
            u[i]=shx
    for i in range(2,4):
        if(u[i]<0):
            u[i]=0
        if(u[i]>shy):
            u[i]=shy     
    return tuple(u)

img = cv2.imread('/C:/Users/KAMAL/Desktop/po3.jfif')
img = cv2.resize(img,(224,224),interpolation = cv2.INTER_CUBIC)
img = img/255.0
img = np.expand_dims(img, axis=0)
ypred = model.predict(img)
l = ypred[1][0]
img = cv2.imread('/content/po3.jfif')
x1 = int(round((l[0]-l[2]/2)*img.shape[1]))
x2 = int(round((l[0]+l[2]/2)*img.shape[1]))
y1 = int(round((l[1]-l[3]/2)*img.shape[0]))
y2 = int(round((l[1]+l[3]/2)*img.shape[0]))
x1,x2,y1,y2 = chx(x1,x2,y1,y2,img.shape[1],img.shape[0])
crop = img[y1:y2,x1:x2]
plt.imshow(crop)